name: deploy-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '14'
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Install deps
        run: pnpm install

      - name: Build app
        env:
          BASE_PATH: http://lvshu.yuusheng.cn/
        run: pnpm run build

      - name: copy dist file with scp
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          ARGS: '-avzr --delete'
          SOURCE: './dist/*'
          TARGET: ${{ secrets.REMOTE_TARGET }}
