name: deploy-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '14'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check
        uses: actions/checkout@v3

      - name: install nodejs
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.x'

      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1

      - name: install deps
        run: yarn

      - name: build app
        run: yarn build

      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          source: 'dist/'
          target: ${{ secrets.REMOTE_TARGET }}
